name: mobile_pos
description: Best POS & Inventory App

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.0.0+10

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl:




  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.5
  barcode_widget: ^2.0.4
  flutter_grid_button: ^2.1.0
  image_picker: ^1.1.2
  flutter_easyloading: ^3.0.5
  flutter_riverpod: ^2.6.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  url_launcher: ^6.3.1
  flutter_feather_icons: ^2.0.0+1
  permission_handler: ^11.3.1
  shared_preferences: ^2.5.2
  restart_app: ^1.3.2
  pinput: ^5.0.1
  nb_utils: ^7.1.2
  youtube_player_flutter: ^9.1.1
  pdf: ^3.11.3
  open_file: ^3.5.10
  path_provider: ^2.0.14
  provider: ^6.1.2
  http: ^1.3.0
  internet_connection_checker_plus: ^2.7.0
  flutter_pdfview: ^1.4.0
  iconly: ^1.0.1
  intl_utils: ^2.8.10
  intl_phone_field: ^3.2.0
  flutter_svg: ^2.0.17
  smooth_page_indicator: ^1.2.0+3
  animated_notch_bottom_bar: ^1.0.3
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.2
  fl_chart: ^0.70.2
  print_bluetooth_thermal: ^1.1.6
  mobile_scanner: ^6.0.6
  excel: ^4.0.6
  flutter_typeahead: ^5.2.0
  esc_pos_utils_plus: ^2.0.4
  printing: ^5.14.2
  file_selector: ^1.0.3
  skeletonizer: ^1.4.3
  upgrader: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0
  icons_launcher: ^3.0.0


flutter:
  uses-material-design: true
  generate: true
  assets:
    - images/
    - assets/


  fonts:
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans/NotoSans-Thin.ttf
          weight: 100
        - asset: fonts/NotoSans/NotoSans-ExtraLight.ttf
          weight: 200
        - asset: fonts/NotoSans/NotoSans-Light.ttf
          weight: 300
        - asset: fonts/NotoSans/NotoSans-Regular.ttf
          weight: 400
        - asset: fonts/NotoSans/NotoSans-Medium.ttf
          weight: 500
        - asset: fonts/NotoSans/NotoSans-SemiBold.ttf
          weight: 600
        - asset: fonts/NotoSans/NotoSans-Bold.ttf
          weight: 700
        - asset: fonts/NotoSans/NotoSans-ExtraBold.ttf
          weight: 800
        - asset: fonts/NotoSans/NotoSans-Black.ttf
          weight: 900

flutter_intl:
  enabled: true


icons_launcher:
  image_path: "images/appIcon.png"
  platforms:
    android:
      enable: true

    ios:
      enable: true
      image_path: "images/appIcon.png"
